import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Navbar } from '@/components/Navbar'; // Import Navbar
import { ThemeProvider } from '@/components/ThemeProvider';

const roboto = Roboto({ 
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.className} min-h-screen flex flex-col relative
        bg-gradient-custom-light dark:bg-gradient-custom-dark
        from-gradient-start-light from-30% via-gradient-middle-light to-gradient-end-light to-70%
        dark:from-gradient-start-dark dark:from-30% dark:via-gradient-middle-dark dark:to-gradient-end-dark dark:to-70%`}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <Navbar />
          <main className="flex-grow relative z-10 pt-16">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
