import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Navbar } from '@/components/Navbar'; // Import Navbar
import { ThemeProvider } from '@/components/ThemeProvider';

const roboto = Roboto({ 
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.className} min-h-screen flex flex-col relative bg-[#0b0c0f]`}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          {/* Background gradient */}
          <div className="absolute inset-0 bg-gradient-to-tl dark:from-[#16181d] from-[#ffffff] from-30% dark:via-[#13291c] dark:to-[#16181d] to-[#ffffff] to-70%"></div>
          
          <Navbar />
          <main className="flex-grow relative z-10 pt-16">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
